# -*- coding: utf-8 -*-
R2 = {
 'Canada':['Ontario','Quebec'], 'Mexico':['Jalisco','Yucatan','Distrito Federal'],
 'Brazil':['Sao Paulo','Bahia'], 'Argentina':['Buenos Aires','Mendoza'],
 'United Kingdom':['Scotland','Wales'], 'France':['Normandie','Bretagne','Île-de-France'],
 'Germany':['Bayern','Sachsen','Berlin'], 'Italy':['Toscana','Sicily','Lazio'],
 'Spain':['Andalucia','Cataluna'], 'Netherlands':['Noord-Holland','Zuid-Holland'],
 'Switzerland':['Zurich','Bern'], 'Sweden':['Skane','Norrbotten'],
 'Norway':['Nordland','Rogaland'], 'Russia':['Sakha (Yakutia)','Krasnodar'],
 'Ukraine':['Kiev','Lviv'], 'Poland':['Masovian','Lesser Poland'],
 'China':['Guangdong','Sichuan'], 'Japan':['Hokkaido','Okinawa'],
 'India':['Kerala','Rajasthan'], 'South Korea':['Jeju','Gyeonggi'],
 'Australia':['Queensland','Tasmania'], 'New Zealand':['Canterbury','Otago'],
 'Indonesia':['Bali','Jawa Timur'], 'Saudi Arabia':['Makkah','Ar Riyad'],
 'Turkey':['Istanbul','Antalya'], 'Greece':['Kriti','Attiki'],
 'Portugal':['Norte','Algarve'],
}
R3 = {
 'Colombia':['Antioquia','Bolivar'], 'Peru':['Cusco','Loreto'],
 'Chile':['Antofagasta','Los Lagos'], 'Venezuela':['Zulia','Bolivar'],
 'Cuba':['Santiago de Cuba','Pinar del Rio'], 'Ireland':['South-West','Border'],
 'Austria':['Tirol','Salzburg'], 'Belgium':['Flemish','Walloon'],
 'Denmark':['Midtjylland','Nordjylland'], 'Finland':['Lapland','Uusimaa'],
 'Czech Republic':['Jihomoravsky','Moravskoslezsky'], 'Hungary':['Baranya','Hajdu-Bihar'],
 'Romania':['Cluj','Constanta'], 'Vietnam':['Lao Cai','Kien Giang'],
 'Thailand':['Chiang Mai','Phuket'], 'Philippines':['Central Visayas (Region VII)','Cordillera Administrative Region (CAR)'],
 'Malaysia':['Sabah','Sarawak'], 'Pakistan':['Sind','Baluchistan'],
 'Bangladesh':['Chittagong','Sylhet'], 'Iran':['Fars','Khuzestan'],
 'Iraq':['Basra','Arbil'], 'Afghanistan':['Kandahar','Balkh'],
 'United Arab Emirates':['Dubay','Abu Dhabi'], 'Kazakhstan':['Almaty','Mangghystau'],
 'Taiwan':[None], 'Sri Lanka':[None],
 'Nepal':[None], 'Uruguay':['Montevideo','Maldonado'],
}
R4 = {
 'Bolivia':['Potosi','Santa Cruz'], 'Ecuador':['Galapagos','Guayas'],
 'Paraguay':['Alto Paraguay','Itapua'], 'Guyana':[None], 'Suriname':[None],
 'Guatemala':['Peten','Solola'], 'Honduras':['Gracias a Dios','Islas de la Bahia'],
 'Nicaragua':['Atlantico Norte','Leon'], 'Costa Rica':[None], 'Panama':[None],
 'Dominican Republic':[None], 'Bulgaria':['Plovdiv','Varna'],
 'Republic of Serbia':[None], 'Croatia':[None],
 'Slovakia':['Kosicky','Zilinsky'], 'Bosnia and Herzegovina':[None],
 'Belarus':['Minsk','Gomel'], 'Lithuania':[None], 'Latvia':[None],
 'Georgia':['Ajaria','Imereti'], 'Armenia':[None], 'Azerbaijan':[None], 'Estonia':[None],
 'Uzbekistan':['Samarkand','Karakalpakstan'], 'Kyrgyzstan':['Osh','Ysyk-Kol'],
 'Mongolia':['Omnogovi','Hovsgol'], 'Myanmar':['Shan','Rakhine'],
 'Cambodia':['Siemreab','Batdambang'], 'Laos':['Louangphrabang','Champasak'],
 'Papua New Guinea':['East New Britain','Morobe'], 'Oman':['Musandam','Dhofar'],
 'Yemen':['Hadramawt','Al Mahrah'], 'Jordan':['Aqaba','Maan'],
 'Syria':['Aleppo','Lattakia'], 'Turkmenistan':['Balkan','Mary'],
 'Tajikistan':['Gorno-Badakhshan','Khatlon'], 'Albania':[None],
 'Macedonia':[None], 'Moldova':[None], 'Iceland':['Austurland','Vesturland'],
}
SMALL = ['Israel','Lebanon','Kuwait','Qatar','Bahrain','Cyprus','Malta','Luxembourg',
 'Andorra','Monaco','San Marino','Liechtenstein','Vatican','Montenegro','Kosovo',
 'Slovenia','Jamaica','Haiti','Trinidad and Tobago','The Bahamas','Barbados','Grenada',
 'Saint Lucia','Saint Vincent and the Grenadines','Dominica','Antigua and Barbuda',
 'Saint Kitts and Nevis','Belize','El Salvador','Singapore','Brunei','Maldives',
 'East Timor','Bhutan','Fiji','Vanuatu','Solomon Islands','Samoa','Tonga',
 'Kiribati','Palau','Nauru','Tuvalu','Marshall Islands','Federated States of Micronesia','Puerto Rico']
AFRICA = ['Algeria','Angola','Benin','Botswana','Burkina Faso','Burundi','Cameroon',
 'Cape Verde','Central African Republic','Chad','Comoros','Democratic Republic of the Congo',
 'Republic of the Congo','Ivory Coast','Djibouti','Egypt','Equatorial Guinea','Eritrea',
 'Swaziland','Ethiopia','Gabon','Gambia','Ghana','Guinea','Guinea Bissau','Kenya',
 'Lesotho','Liberia','Libya','Madagascar','Malawi','Mali','Mauritania','Mauritius',
 'Morocco','Mozambique','Namibia','Niger','Nigeria','Rwanda','Sao Tome and Principe',
 'Senegal','Seychelles','Sierra Leone','Somalia','South Africa','S. Sudan','Sudan',
 'United Republic of Tanzania','Togo','Tunisia','Uganda','Zambia','Zimbabwe','Western Sahara']

PALESTINE = [('Palestine', ['West Bank','Gaza Strip'])]
